project:
  type: website
  output-dir: docs

website:
  title: "About Me"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - project.qmd
      - hobby.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

